require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/planets", type: :request do

  # Planet. As you add validations to Planet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Earth', gravitational_accelaration: 9.8, has_fuel: true }
  }

  let(:invalid_attributes) {
    { name: 'Jupiter', gravitational_accelaration: -30, has_fuel: true }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Planet.create! valid_attributes
      get planets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      planet = Planet.create! valid_attributes
      get planet_url(planet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_planet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      planet = Planet.create! valid_attributes
      get edit_planet_url(planet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Planet" do
        expect {
          post planets_url, params: { planet: valid_attributes }
        }.to change(Planet, :count).by(1)
      end

      it "redirects to the created planet" do
        post planets_url, params: { planet: valid_attributes }
        expect(response).to redirect_to(planet_url(Planet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Planet" do
        expect {
          post planets_url, params: { planet: invalid_attributes }
        }.to change(Planet, :count).by(0)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested planet" do
      planet = Planet.create! valid_attributes
      expect {
        delete planet_url(planet)
      }.to change(Planet, :count).by(-1)
    end

    it "redirects to the planets list" do
      planet = Planet.create! valid_attributes
      delete planet_url(planet)
      expect(response).to redirect_to(planets_url)
    end
  end
end
